### ISSUE TITLE
Selenium Grid Not Working

### ISSUE THREAD

**Issue by primitivetypo** [burakkaygusuz/appium-parallel-test-execution#9]
Hi @burakkaygusuz,  Thanks for the awesome projects. I had a quick question:

I followed the set up and tests run in parallel but on selenium console, i don't see the sessions.
Normally we need to start `AndroidDriver` on grid url but in your case, you start it on `localhost:4723`

When i change the line on base test to below this 
`driverThreadLocal.set(new AndroidDriver(new URL("http://localhost:5555"), options));` 

 then test fail with error below

`[ERROR]   LoginTest>BaseTest.setUp:33 » SessionNotCreated Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.`

However, in this case, i see the sessions started on grid url : http://localhost:5555/ui#/sessions

I am on a mac and followed all steps to set up Appium 2.0 and start grid with same toml code you have.

Any idea how to make it work with selenium grid via relay?

**Comment by primitivetypo** [comment]
@burakkaygusuz Thanks for looking into this. I am also seeing the same error even with the updated docker file.

Please keep me updated if you find solution.
Thanks.

**Comment by primitivetypo** [comment]
hey @burakkaygusuz Did you get this work? I tried latest changes but still see an error

`[ERROR]   LoginTest>BaseTest.setUp:33 » SessionNotCreated Could not start a new session. Response code 500. Message: Could not start a new session. New session request timed out`

Any idea what could be causing the issue?

**Comment by burakkaygusuz** [comment]
@primitivetypo Could you please review the configuration in this example? https://github.com/jlipps/appium-grid-example

**Comment by primitivetypo** [comment]
@burakkaygusuz I think it is an issue with selenium core rather than the configuration. I build locally the selenium trunk code and generate latest selenium.jar and it works very well with the config. I expect the issue to be fixed in the next selenium release via docker and we should be good to go.
Until then building latest from trunk and manually running without docker works as expected.

**Comment by burakkaygusuz** [comment]
https://github.com/appium/appium/issues/17445

**Comment by burakkaygusuz** [comment]
https://github.com/appium/appium/issues/17445

**Comment by primitivetypo** [comment]
@burakkaygusuz I think you will get better feedback in selenium or selenium-docker repositories as this appears not be related to appium.

**Comment by burakkaygusuz** [comment]
https://github.com/SeleniumHQ/docker-selenium/issues/1669

**Comment by primitivetypo** [comment]
@burakkaygusuz I had an unrelated question. How dod you convert appium server commands to the yaml file? I am trying to add arguments for `allow-insecure` . It works with CLI but not using the config.yaml.
Here is the command that works if starting appium from CLI
`appium server --allow-insecure=adb_shell,chromedriver_autodownload `

And from appium logs i see correctly the two non default server arguments updated:
```
info Appium Welcome to Appium v2.0.0-beta.21 (REV 3748bed378401ed75abdf32bcb3d2674d854a6f9)
info Appium Non-default server args:
info Appium   allowInsecure: {
info Appium     0: adb_shell
info Appium     1: chromedriver_autodownload
info Appium   }
info Appium Attempting to load driver uiautomator2...
```

However, issue is with starting from config as below:
```
server:
  port: 4723
  keep-alive-timeout: 80
  session-override: true
  allow-insecure: ['adb_shell', 'chromedriver_autodownload']
  use-drivers:
    - uiautomator2
```
When i run 
` appium server --config appium_1.yml`   don't see those server arguments activated
Any idea what i might be missing?

**Comment by primitivetypo** [comment]
@burakkaygusuz Have you looked into [Appium device farm?](https://github.com/AppiumTestDistribution/appium-device-farm) ? it appears to be build for Appium 2.0 and has better functionality than selenium hub without the complexities that come with selenium hub. What do you think?

**Comment by primitivetypo** [comment]
I have delete the project on my repo. It was never my intention to copy it as one of my own. I always fork the project. I apologies for any disrespect on my part if any.

**Comment by primitivetypo** [comment]
Also @burakkaygusuz I don't need to fork it since I moved to implementing the parallel test using `appium-device-farm` plugin that i had shared with you that you deleted. I am sorry again.

**Comment by primitivetypo** [comment]
Feel free to delete this issue too.
